// Generated by gencpp from file osi3_bridge/Orientation3d.msg
// DO NOT EDIT!


#ifndef OSI3_BRIDGE_MESSAGE_ORIENTATION3D_H
#define OSI3_BRIDGE_MESSAGE_ORIENTATION3D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace osi3_bridge
{
template <class ContainerAllocator>
struct Orientation3d_
{
  typedef Orientation3d_<ContainerAllocator> Type;

  Orientation3d_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  Orientation3d_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::osi3_bridge::Orientation3d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::osi3_bridge::Orientation3d_<ContainerAllocator> const> ConstPtr;

}; // struct Orientation3d_

typedef ::osi3_bridge::Orientation3d_<std::allocator<void> > Orientation3d;

typedef boost::shared_ptr< ::osi3_bridge::Orientation3d > Orientation3dPtr;
typedef boost::shared_ptr< ::osi3_bridge::Orientation3d const> Orientation3dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::osi3_bridge::Orientation3d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::osi3_bridge::Orientation3d_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::osi3_bridge::Orientation3d_<ContainerAllocator1> & lhs, const ::osi3_bridge::Orientation3d_<ContainerAllocator2> & rhs)
{
  return lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::osi3_bridge::Orientation3d_<ContainerAllocator1> & lhs, const ::osi3_bridge::Orientation3d_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace osi3_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::osi3_bridge::Orientation3d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::osi3_bridge::Orientation3d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::osi3_bridge::Orientation3d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::osi3_bridge::Orientation3d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osi3_bridge::Orientation3d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osi3_bridge::Orientation3d_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::osi3_bridge::Orientation3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eeec8b25a660789a89540dedcb2b06d6";
  }

  static const char* value(const ::osi3_bridge::Orientation3d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeeec8b25a660789aULL;
  static const uint64_t static_value2 = 0x89540dedcb2b06d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::osi3_bridge::Orientation3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "osi3_bridge/Orientation3d";
  }

  static const char* value(const ::osi3_bridge::Orientation3d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::osi3_bridge::Orientation3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::osi3_bridge::Orientation3d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::osi3_bridge::Orientation3d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Orientation3d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::osi3_bridge::Orientation3d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::osi3_bridge::Orientation3d_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OSI3_BRIDGE_MESSAGE_ORIENTATION3D_H
