(cl:in-package object_list-msg)
(cl:export '(SENSOR_ID-VAL
          SENSOR_ID
          SENSORTYPE-VAL
          SENSORTYPE
          POSX_VARIANCE-VAL
          POSX_VARIANCE
          POSY_VARIANCE-VAL
          POSY_VARIANCE
          VELX_VARIANCE-VAL
          VELX_VARIANCE
          VELY_VARIANCE-VAL
          VELY_VARIANCE
          TRUST_EXISTANCE-VAL
          TRUST_EXISTANCE
          TRUST_CAR-VAL
          TRUST_CAR
          TRUST_TRUCK-VAL
          TRUST_TRUCK
          TRUST_MOTORCYCLE-VAL
          TRUST_MOTORCYCLE
          TRUST_BICYCLE-VAL
          TRUST_BICYCLE
          TRUST_PEDESTRIAN-VAL
          TRUST_PEDESTRIAN
          TRUST_STATIONARY-VAL
          TRUST_STATIONARY
          TRUST_OTHER-VAL
          TRUST_OTHER
))