# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from osi3_bridge/TrafficUpdateMovingObject.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import osi3_bridge.msg
import std_msgs.msg

class TrafficUpdateMovingObject(genpy.Message):
  _md5sum = "b26e20bf46b692e8759e85b824c5ffc2"
  _type = "osi3_bridge/TrafficUpdateMovingObject"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
osi3_bridge/MovingObject object

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: osi3_bridge/MovingObject
uint64 id
osi3_bridge/Dimension3d dimension
geometry_msgs/Vector3 position
osi3_bridge/Orientation3d orientation
geometry_msgs/Vector3 velocity
geometry_msgs/Vector3 acceleration
uint8 type

uint8 TYPE_UNKNOWN = 0
uint8 TYPE_OTHER = 1
uint8 TYPE_CAR = 2
uint8 TYPE_PEDESTRIAN = 3
uint8 TYPE_ANIMAL = 4
uint8 TYPE_TRUCK = 5
uint8 TYPE_TRAILER = 6
uint8 TYPE_MOTORBIKE = 7
uint8 TYPE_BICYCLE = 8
uint8 TYPE_BUS = 9
uint8 TYPE_TRAM = 10
uint8 TYPE_TRAIN = 11
uint8 TYPE_WHEELCHAIR = 12


================================================================================
MSG: osi3_bridge/Dimension3d
float64 length
float64 width
float64 height

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: osi3_bridge/Orientation3d
float64 roll
float64 pitch
float64 yaw
"""
  __slots__ = ['header','object']
  _slot_types = ['std_msgs/Header','osi3_bridge/MovingObject']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,object

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TrafficUpdateMovingObject, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.object is None:
        self.object = osi3_bridge.msg.MovingObject()
    else:
      self.header = std_msgs.msg.Header()
      self.object = osi3_bridge.msg.MovingObject()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Q15dB().pack(_x.object.id, _x.object.dimension.length, _x.object.dimension.width, _x.object.dimension.height, _x.object.position.x, _x.object.position.y, _x.object.position.z, _x.object.orientation.roll, _x.object.orientation.pitch, _x.object.orientation.yaw, _x.object.velocity.x, _x.object.velocity.y, _x.object.velocity.z, _x.object.acceleration.x, _x.object.acceleration.y, _x.object.acceleration.z, _x.object.type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.object is None:
        self.object = osi3_bridge.msg.MovingObject()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 129
      (_x.object.id, _x.object.dimension.length, _x.object.dimension.width, _x.object.dimension.height, _x.object.position.x, _x.object.position.y, _x.object.position.z, _x.object.orientation.roll, _x.object.orientation.pitch, _x.object.orientation.yaw, _x.object.velocity.x, _x.object.velocity.y, _x.object.velocity.z, _x.object.acceleration.x, _x.object.acceleration.y, _x.object.acceleration.z, _x.object.type,) = _get_struct_Q15dB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Q15dB().pack(_x.object.id, _x.object.dimension.length, _x.object.dimension.width, _x.object.dimension.height, _x.object.position.x, _x.object.position.y, _x.object.position.z, _x.object.orientation.roll, _x.object.orientation.pitch, _x.object.orientation.yaw, _x.object.velocity.x, _x.object.velocity.y, _x.object.velocity.z, _x.object.acceleration.x, _x.object.acceleration.y, _x.object.acceleration.z, _x.object.type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.object is None:
        self.object = osi3_bridge.msg.MovingObject()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 129
      (_x.object.id, _x.object.dimension.length, _x.object.dimension.width, _x.object.dimension.height, _x.object.position.x, _x.object.position.y, _x.object.position.z, _x.object.orientation.roll, _x.object.orientation.pitch, _x.object.orientation.yaw, _x.object.velocity.x, _x.object.velocity.y, _x.object.velocity.z, _x.object.acceleration.x, _x.object.acceleration.y, _x.object.acceleration.z, _x.object.type,) = _get_struct_Q15dB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_Q15dB = None
def _get_struct_Q15dB():
    global _struct_Q15dB
    if _struct_Q15dB is None:
        _struct_Q15dB = struct.Struct("<Q15dB")
    return _struct_Q15dB
