classdef ObjectsList < robotics.ros.Message
    %ObjectsList MATLAB implementation of object_list/ObjectsList
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'object_list/ObjectsList' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '214beebd8035ba15b863e0e4f0dac47e' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        ObjectListObjectListClass = robotics.ros.msg.internal.MessageFactory.getClassForType('object_list/ObjectList') % Dispatch to MATLAB class for message type object_list/ObjectList
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        ObjList
    end
    
    properties (Access = protected)
        Cache = struct('Header', [], 'ObjList', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Header', 'ObjList'} % List of non-constant message properties
        ROSPropertyList = {'header', 'obj_list'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ObjectsList(msg)
            %ObjectsList Construct the message object ObjectsList
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'ObjectsList', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function objlist = get.ObjList(obj)
            %get.ObjList Get the value for property ObjList
            if isempty(obj.Cache.ObjList)
                javaArray = obj.JavaMessage.getObjList;
                array = obj.readJavaArray(javaArray, obj.ObjectListObjectListClass);
                obj.Cache.ObjList = feval(obj.ObjectListObjectListClass, array);
            end
            objlist = obj.Cache.ObjList;
        end
        
        function set.ObjList(obj, objlist)
            %set.ObjList Set the value for property ObjList
            if ~isvector(objlist) && isempty(objlist)
                % Allow empty [] input
                objlist = feval([obj.ObjectListObjectListClass '.empty'], 0, 1);
            end
            
            validateattributes(objlist, {obj.ObjectListObjectListClass}, {'vector'}, 'ObjectsList', 'ObjList');
            
            javaArray = obj.JavaMessage.getObjList;
            array = obj.writeJavaArray(objlist, javaArray, obj.ObjectListObjectListClass);
            obj.JavaMessage.setObjList(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.ObjList)
                obj.Cache.ObjList = [];
                obj.Cache.ObjList = obj.ObjList;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
            obj.Cache.ObjList = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
            cpObj.ObjList = copy(obj.ObjList);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
            ObjListCell = arrayfun(@(x) feval([obj.ObjectListObjectListClass '.loadobj'], x), strObj.ObjList, 'UniformOutput', false);
            obj.ObjList = vertcat(ObjListCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Header = saveobj(obj.Header);
            strObj.ObjList = arrayfun(@(x) saveobj(x), obj.ObjList);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.object_list.ObjectsList.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.object_list.ObjectsList;
            obj.reload(strObj);
        end
    end
end
