classdef TrafficUpdateMovingObject < robotics.ros.Message
    %TrafficUpdateMovingObject MATLAB implementation of osi3_bridge/TrafficUpdateMovingObject
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'osi3_bridge/TrafficUpdateMovingObject' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'b26e20bf46b692e8759e85b824c5ffc2' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        Osi3BridgeMovingObjectClass = robotics.ros.msg.internal.MessageFactory.getClassForType('osi3_bridge/MovingObject') % Dispatch to MATLAB class for message type osi3_bridge/MovingObject
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        Object
    end
    
    properties (Access = protected)
        Cache = struct('Header', [], 'Object', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Header', 'Object'} % List of non-constant message properties
        ROSPropertyList = {'header', 'object'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = TrafficUpdateMovingObject(msg)
            %TrafficUpdateMovingObject Construct the message object TrafficUpdateMovingObject
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'TrafficUpdateMovingObject', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function object = get.Object(obj)
            %get.Object Get the value for property Object
            if isempty(obj.Cache.Object)
                obj.Cache.Object = feval(obj.Osi3BridgeMovingObjectClass, obj.JavaMessage.getObject);
            end
            object = obj.Cache.Object;
        end
        
        function set.Object(obj, object)
            %set.Object Set the value for property Object
            validateattributes(object, {obj.Osi3BridgeMovingObjectClass}, {'nonempty', 'scalar'}, 'TrafficUpdateMovingObject', 'Object');
            
            obj.JavaMessage.setObject(object.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Object)
                obj.Cache.Object.setJavaObject(object.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
            obj.Cache.Object = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
            cpObj.Object = copy(obj.Object);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
            obj.Object = feval([obj.Osi3BridgeMovingObjectClass '.loadobj'], strObj.Object);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Header = saveobj(obj.Header);
            strObj.Object = saveobj(obj.Object);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.osi3_bridge.TrafficUpdateMovingObject.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.osi3_bridge.TrafficUpdateMovingObject;
            obj.reload(strObj);
        end
    end
end
