(cl:defpackage osi3_bridge-msg
  (:use )
  (:export
   "<DIMENSION3D>"
   "DIMENSION3D"
   "<GROUNDTRUTHMOVINGOBJECTS>"
   "GROUNDTRUTHMOVINGOBJECTS"
   "<MOVINGOBJECT>"
   "MOVINGOBJECT"
   "<ORIENTATION3D>"
   "ORIENTATION3D"
   "<TRAFFICUPDATEMOVINGOBJECT>"
   "TRAFFICUPDATEMOVINGOBJECT"
  ))

